#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=15gb,walltime=14:00:00
#PBS -N trekker

set -e
set -x

time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./input_data_generator.sh

time singularity exec -e docker://brainlife/trekker:0.4 ./run.sh

time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./convert_output_to_tck.sh
