#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=30gb,walltime=36:00:00
#PBS -N app-trekker

set -x
set -e

if [ ! -f csf_bin.nii.gz ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./preprocess.sh
fi

time singularity exec -e docker://brainlife/trekker:0.6 ./tracking.py

if [ ! -f ./track/track.tck ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./convert.sh
fi

if [ -f ./track/track.tck ]; then
	echo "complete"
	exit 0
else
	echo "tracking failed"
	exit 1
fi
